baseURL = "http://localhost:1313/" # Remplacer par "https://gigaboulet.blog/" en production
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
disqusShortname = "guangmean"   # Optional
title = "Gigaboulet - Les Flops Légendaires"

staticDir = ["static", "themes/Niello/static"]

theme = "Niello"

[languages]
  [languages.fr]
    languageCode = "fr-fr"
    LanguageName = "🇫🇷 Français"
    contentDir = "content/fr"
    weight = 1
	[[languages.fr.menus.main]]
		name = 'exampleHome'
		pageRef = '/'
		weight = 1
	[[languages.fr.menus.main]]
		name = 'exampleCategories'
		pageRef = '/categories'
		weight = 2
	[[languages.fr.menus.main]]
		name = 'exampleTags'
		pageRef = '/tags'
		weight = 3
	[languages.en]
		languageCode = "en-us"
		LanguageName = "🇺🇸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'exampleHome'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'exampleCategories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'exampleTags'
			pageRef = '/tags'
			weight = 3

[params]
[params.google]
	google_ad_client = "******"
	ga4 = "******"
[params.bannershowcase]
	categories = ["Example 1 - EN"]
	limit = 2
[params.email]
	contact = "example@gmail.com"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie"]

copyright = "&#xA9; 2019 ~ 2024 by www.example.com All Rights Reserved."
sharethis = "******"

[outputs]
  home = ["HTML", "JSON"]   # Optional - JSON just for search